require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout/LineLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  
Metrics/AbcSize:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 20